first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views
from django.urls import path

#Template URLs
app_name = 'first_app'

urlpatterns =[
    # path('index', views.index,name="index"),
    # #path('help', views.help,name="help"),
    # path('formpage', views.form_name_view,name="form_name"),
    path('register', views.register,name="register"),
    path('user_login', views.user_login,name="user_login"),



]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include

urlpatterns = [
    path('', views.index,name='index'),
    path('logout', views.user_logout,name='logout'),
    path('special', views.special,name='special'),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),

]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class Topic(models.Model):
#     top_name = models.CharField(max_length=264,unique=True)
#
#     def __str__(self):
#         return self.top_name
#
# class Webpage(models.Model):
#     topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
#     name = models.CharField(max_length=264,unique=True)
#     url = models.URLField(unique=True)
#
#     def __str__(self):
#         return self.name
#
# class AccessRecord(models.Model):
#     name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
#     date = models.DateField()
#
#     def __str__(self):
#         return str(self.date)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional Parameters
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/second_app/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

# class  FormName(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     text = forms.CharField(widget=forms.Textarea)
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
#from first_app.models import AccessRecord,Topic,Webpage
from first_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.
# def index(request):
#     webpages_list = AccessRecord.objects.order_by('date')
#     date_dict = {'access_records':webpages_list}
#     return render(request,'first_app/index.html',context=date_dict)
#
# def help(request):
#     return render(request,'first_app/help.html')

def index(request):
    return render(request,'first_app/index.html')

# def form_name_view(request):
#     form = forms.FormName()
#     return render(request,'first_app/form_page.html',{'form':form})

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile_user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'first_app/register.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})

@login_required
def special(request):
    return HttpResponse('Your logged in')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("someone tried to login and falied")
            print("username {} and password {}".format(username,password))
            return HttpResponse("Invalid login credentials")

    else:
        return render(request,'first_app/login.html',{} )

first_project/second_app/views.py
from django.shortcuts import render

# Create your views here.

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'first_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>
          {% endif %}




        </ul>

      </div>

    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
  </head>
  <body>
    <div class="container">
      {{form}}
    </div>
  </body>
</html>

first_project/templates/first_app/help.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> This is a help page </h1>
  </body>
</html>

first_project/templates/first_app/index.html
{% extends "first_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>
{% endblock %}

<!-- <!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Django Level Two</title>
    <link rel="stylesheet" href="{%static "css/mystyle.css" %}">
  </head>
  <body>
    <h1>Hi! Welcome to Django level two</h1>
    <h2>Here are your access records</h2>
    <div class="djangtwo">
      {% if access_records%}
        <table>
          <thead>
            <th>Site Name</th>
            <th>Date Accessed</th>
          </thead>
          {% for acc in access_records %}
            <tr>
              <td>{{acc.name}}</td>
              <td>{{acc.date}}</td>
            </tr>
          {% endfor %}
        </table>
        {% else %}
        <p>No Acess Records Found</p>
        {% endif %}

    </div>


  </body>
</html> -->

first_project/templates/first_app/login.html
{% extends "first_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password"></label>
    <input type="password" name="password">
    <input type="submit" name="" value="Login">

  </form>
</div>
{% endblock %}

first_project/templates/first_app/register.html
{% extends "first_app/base.html" %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thanks For Registering</h1>
  {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the Form :</h3>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">

    </form>
  {% endif %}
</div>
{% endblock %}